Verifying username and password

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,7 +22,10 @@ jobs:
         run: pytest
         
       - name: Login to Docker Hub
-        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+      - run: |
+          test -n "${{ secrets.DOCKER_USERNAME }}" || echo "Username missing"
+          test -n "${{ secrets.DOCKER_PASSWORD }}" || echo "Password missing"
+          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
       - name: Build Docker Image
         run: docker build -t ehsanelahi249/week3-app:${{ github.sha }} .
